### ISSUE TITLE
[Android] Icon component not working properly

### ISSUE THREAD

**Issue by bhiesl** [expo/vector-icons#176]
As in the title stated the Icons are not working properly on Android. I already upgraded expo to 41.0.0 and initialised a new blank project via 
`expo init testProject`

Next I added following line to my App.js imports:
`import { Ionicons } from "@expo/vector-icons"`

After setting everything up my App.js rendering method looks like this:

```
export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
      <Ionicons name="send" size={32}/>
    </View>
  );
}
```

Looks good to me.

I've already tried the sample code provided by: https://docs.expo.io/guides/icons/
But still on my local Android emulator the icons are not rendered.
iOS and Web works without any problems.

Output on the console after opening the Android app:

_[Unhandled promi]e rejection: Error: Unexpected status line: !�
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper
at node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-file-system/build/FileSystem.js:105:17 in downloadAsync
at node_modules/expo-file-system/build/FileSystem.js:101:7 in downloadAsync
at node_modules/expo-asset/build/PlatformUtils.js:49:25 in _downloadAsyncManagedEnv
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue_

**Comment by FreakyHarsh** [comment]
I'm facing the same issue.

**Comment by alexcoady** [comment]
I'm also getting this with:
- `"expo": "~42.0.0"`

The console errors for Android (emulator) are (sic): 
```
[Unhandled promi]e rejection: Error: Unexpected status line: !�
```

The console errors using Expo go on my actual iPhone 12 pro:
```
[Unhandled promise rejection: Error: Downloaded file for asset 'Ionicons.ttf' Located at http://192.168.1.208:19000/assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.ttf?platform=ios&hash=b3263095df30cb7db78c613e73f9499a?platform=ios&dev=true&hot=false&minify=false failed MD5 integrity check]
```

And yet on the iOS simulator it works perfectly.
