### ISSUE TITLE
Error when using in combination with Jest

### ISSUE THREAD

**Issue by evert-smit** [expo/vector-icons#52]
This issue might be related to #39 - I'm running into trouble with a similar setup. For some reason, Jest is unable to load vector-icons correctly.

The error is slightly different, but the problem goes away when I remove vector-icons from the file it's used in.

"@expo/vector-icons": "^6.3.1",
"expo": "^27.0.1",
"jest-expo": "~27.0.0",

Error message:
```
TypeError: TaskQueue: Error with task : Cannot read property 'Object.<anonymous>' of null
    at Runtime._execModule
```

The test itself is simple:
```

import React from 'react';
import App from '../App';

import renderer from 'react-test-renderer';

describe('<App />', () => {
  it('renders correctly', () => {
    const rendered = renderer.create(<App />).toJSON();
    expect(rendered).toMatchSnapshot();
  });
});
```

Is anyone else experiencing this issue as well?

**Comment by brentvatne** [comment]
this is old, sorry for not replying sooner. can you share a reproducible example if this still exists? It doesn't happen for me on sdk30

**Comment by srivastavaaviral1cc** [comment]
I'm also facing the same issue. 

```
 Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /MyAwesomeProject/node_modules/@expo/vector-icons/Ionicons.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import glyphMap from './vendor/react-native-vector-icons/glyphmaps/Ionicons.json';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.require (node_modules/native-base/dist/src/basic/IconNB.js:1:1094)
      at Object.<anonymous> (node_modules/native-base/dist/src/index.js:1:1891)

```

Package versions: 

```
"expo": "28.0.0",
"jest": "23.4.2",
"ts-jest": "23.1.4", // Using expo with a typescript project.
"babel-jest": "23.4.2",
```

**Comment by brentvatne** [comment]
for anyone who encounters this in the future

> can you share a reproducible example if this still exists? It doesn't happen for me on sdk30

**Comment by DianaKoenraadt** [comment]
I have a related issue.

```
 ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import createIconSet from './createIconSet';
                                                                                                    ^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/@expo/vector-icons/src/Icons.ts:1:1)
```

Reproduction scenario is easy. In your `Bla.test.js`, import this at the top:

`import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
`

**Comment by brentvatne** [comment]
you need to use the jest expo preset or add the library to your jest transform paths :)

see https://stackoverflow.com/help/mcve for more info on how to create a reproducible example. it's easy to see that this is not as simple to reproduce as you suggest by initializing a project with the tabs template using `expo init` and then running `yarn test` - notice that we import from @expo/vector-icons in App.js and the tests run as expected
